spring.application.name=cliente

# Porta do CLIENTE (o servidor Imobiliaria roda em 8080)
server.port=8081

# URL base da API REST do servidor Imobiliaria consumida via RestClient
api.base-url=http://localhost:8080

# Desativa cache do Thymeleaf durante o desenvolvimento
spring.thymeleaf.cache=false
